#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install pytest
            - pip install pytest-html
            - pip install selenium
            - pytest --html=reports/report.html test.py
          artifacts:
          - reports/**
          services:
            - chrome
definitions:
  services:
    chrome:
      image: selenium/standalone-chrome

