# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNewTest():

    def setup_method(self, method):
        #self.driver = webdriver.Chrome()
        self.driver = webdriver.Remote('http://localhost:4444/wd/hub',options=webdriver.ChromeOptions())
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_newTest(self):
        self.driver.get("https://www.saucedemo.com/v1/")
        self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"username\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"username\"]").send_keys("standard_user")
        self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"password\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.ID, "login-button").click()
        self.driver.find_element(By.CSS_SELECTOR, ".product_label").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".product_label").text == "Products"
  
